global:
  registry: us.icr.io
  imagePullSecrets:
    - all-icr-io

ingress:
  web:
    enabled: false
    domain: vizivault.anontech.domain
    tls:
      enabled: false
      secretName: tls-secret
    annotations: {}
  api:
    enabled: false
    domain: api.anontech.domain
    tls:
      enabled: false
      secretName: tls-secret
    annotations: {}

# ViziVault Application
vizivault:
  name: "webapp"
  image:
    repository: anontech/vault-enterprise
    tag: latest
    pullPolicy: IfNotPresent
  admin:
    username: vizivault
    password:
    email: "admin@anontech.domain"
    name: "ViziVault Admin"
  service:
    type: ClusterIP

# Vault API
api:
  name: "api"
  replicas: 1
  image:
    repository: anontech/nox
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

# Notification Service
alerts:
  name: "alerts"
  image:
    repository: anontech/nova
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

# Cipher Encryption Service
cipher:
  name: "cipher"
  image:
    repository: anontech/cipher
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

# Arbiter Validation Service
arbiter:
  name: "arbiter"
  image:
    repository: anontech/arbiter
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

initializer:
  image:
    repository: anontech/initializer
    tag: 0.1.6
    pullPolicy: IfNotPresent

# Database Configuration
# These values will be ignored if mongodb.enabled is set to true
database:
  authDb: admin
  username: vizivault-platform
  password:
  host: localhost
  port: 27017
  secretName:

# RabbitMQ Configuration
# These values will be ignored if rabbitmq.enabled is set to true
rabbit:
  username: user
  password:
  host: rabbitmq.local
  port: 5672
  secretName:


# MongoDB Configuration
# https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
mongodb:
  enabled: true
  architecture: standalone
  useStatefulSet: true
  auth:
    database: admin
    username: vizivault-platform
  initdbScriptsConfigMap: vizivault-platform-initdb

# RabbitMQ Configuration
# https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml
rabbitmq:
  enabled: true
  auth:
    username: vizivault-platform
