apiVersion: v1
kind: Service
metadata:
  name: vizivault-platform-alerts-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "vizivault-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.alerts.service.type }}
  ports:
    - name: vizivault-alerts-http
      port: 80
      protocol: TCP
      targetPort: http
    - name: vizivault-alerts-ws
      port: 81
      protocol: TCP
      targetPort: ws
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ printf "vizivault-%s" .Values.alerts.name }}