apiVersion: v1
kind: Secret
metadata:
  name: vizivault-platform-secrets
  labels:
    app.kubernetes.io/name: vizivault-platform-secrets
    helm.sh/chart: {{ include "vizivault-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  vizivault-admin-password: {{ b64enc (include "vizivault-platform.password" .) | quote }}
  token-signing-key: {{ b64enc (include "vizivault-platform.password" .) | quote }}