apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vizivault-platform.fullname" (dict "root" . "app" .Values.vizivault.name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.vizivault.name }}
    helm.sh/chart: {{ include "vizivault-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "vizivault-%s" .Values.vizivault.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "vizivault-%s" .Values.vizivault.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ printf "vizivault-%s" .Values.vizivault.name }}
          image: {{ include "vizivault-platform.image" (dict "root" .Values.image "app" .Values.vizivault.image ) }}
          imagePullPolicy: {{ .Values.vizivault.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VIZIVAULT_ADMIN_USERNAME
              value: {{ .Values.vizivault.admin.username | quote }}
            - name: VIZIVAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vizivault-platform-secrets
                  key: vizivault-admin-password
            - name: VIZIVAULT_ADMIN_EMAIL
              value: {{ .Values.vizivault.admin.email | quote }}
            - name: VIZIVAULT_ADMIN_NAME
              value: {{ .Values.vizivault.admin.name | quote }}
            - name: SPRING_DATA_MONGODB_HOST
              value: {{ include "vizivault-platform.databaseHost" . | quote }}
            - name: SPRING_DATA_MONGODB_PORT
              value: {{ include "vizivault-platform.databasePort" . | quote }}
            - name: SPRING_DATA_MONGODB_USERNAME
              value: root
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vizivault-platform.databaseSecretName" . }}
                  key: mongodb-root-password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: {{ include "vizivault-platform.authDb" . | quote }}
            - name: SPRING_DATA_MONGODB_DATABASE
              value: webapp
            - name: SPRING_RABBITMQ_HOST
              value: {{ include "vizivault-platform.rabbitHost" . | quote }}
            - name: SPRING_RABBITMQ_PORT
              value: {{ include "vizivault-platform.rabbitPort" . | quote }}
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ include "vizivault-platform.rabbitUser" . | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "vizivault-platform.rabbitSecretName" . }}
                  key: rabbitmq-password
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              value: "/"
      {{- include "vizivault-platform.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
