apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vizivault-platform.fullname" (dict "root" . "app" .Values.arbiter.name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.arbiter.name }}
    helm.sh/chart: {{ include "vizivault-platform.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "vizivault-%s" .Values.arbiter.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "vizivault-%s" .Values.arbiter.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "vizivault-platform.image" (dict "root" .Values "app" .Values.arbiter.image ) }}
          imagePullPolicy: {{ .Values.arbiter.image.pullPolicy }}
          env:
            - name: HOSTNAME
              value: 0.0.0.0
            - name: DATABASE_HOST
              value: {{ include "vizivault-platform.databaseHost" . | quote }}
            - name: DATABASE_PORT
              value: {{ include "vizivault-platform.databasePort" . | quote }}
            - name: DATABASE_AUTH_SOURCE
              value: {{ include "vizivault-platform.authDb" . | quote }}
            - name: DATABASE_USER
              value: vizivault-platform
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vizivault-platform.databaseSecretName" . }}
                  key: mongodb-password
            - name: MONGO_URI
              value: {{ printf "mongodb://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/?authSource=$(DATABASE_AUTH_SOURCE)"}}
            - name: MONGO_AUTH_DB
              value: webapp
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- include "vizivault-platform.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
